package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Assignment generated by hbm2java
 */
@Entity
@Table(name = "assignment", schema = "public")
public class Assignment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1448509333323429267L;
	private AssignmentId id;
	private Permission permission;
	private Role role;
	private Date asTimestamp;

	public Assignment() {
	}

	public Assignment(AssignmentId id, Permission permission, Role role, Date asTimestamp) {
		this.id = id;
		this.permission = permission;
		this.role = role;
		this.asTimestamp = asTimestamp;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "prId", column = @Column(name = "pr_id", nullable = false)),
			@AttributeOverride(name = "roId", column = @Column(name = "ro_id", nullable = false)) })
	public AssignmentId getId() {
		return this.id;
	}

	public void setId(AssignmentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pr_id", nullable = false, insertable = false, updatable = false)
	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ro_id", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "as_timestamp", nullable = false, length = 35)
	public Date getAsTimestamp() {
		return this.asTimestamp;
	}

	public void setAsTimestamp(Date asTimestamp) {
		this.asTimestamp = asTimestamp;
	}

}
