package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssignmentId generated by hbm2java
 */
@Embeddable
public class AssignmentId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3945907103281196193L;
	private short prId;
	private short roId;

	public AssignmentId() {
	}

	public AssignmentId(short prId, short roId) {
		this.prId = prId;
		this.roId = roId;
	}

	@Column(name = "pr_id", nullable = false)
	public short getPrId() {
		return this.prId;
	}

	public void setPrId(short prId) {
		this.prId = prId;
	}

	@Column(name = "ro_id", nullable = false)
	public short getRoId() {
		return this.roId;
	}

	public void setRoId(short roId) {
		this.roId = roId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssignmentId))
			return false;
		AssignmentId castOther = (AssignmentId) other;

		return (this.getPrId() == castOther.getPrId()) && (this.getRoId() == castOther.getRoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrId();
		result = 37 * result + this.getRoId();
		return result;
	}

}
