package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorityId generated by hbm2java
 */
@Embeddable
public class AuthorityId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -162950840385584116L;
	private long peId;
	private short roId;

	public AuthorityId() {
	}

	public AuthorityId(long peId, short roId) {
		this.peId = peId;
		this.roId = roId;
	}

	@Column(name = "pe_id", nullable = false)
	public long getPeId() {
		return this.peId;
	}

	public void setPeId(long peId) {
		this.peId = peId;
	}

	@Column(name = "ro_id", nullable = false)
	public short getRoId() {
		return this.roId;
	}

	public void setRoId(short roId) {
		this.roId = roId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorityId))
			return false;
		AuthorityId castOther = (AuthorityId) other;

		return (this.getPeId() == castOther.getPeId()) && (this.getRoId() == castOther.getRoId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPeId();
		result = 37 * result + this.getRoId();
		return result;
	}

}
