package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonView;
import com.hiveag.geepy.util.View;


/**
 * Bike generated by hbm2java
 */
@Entity
@Table(name = "bike", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "bi_serial"))
public class Bike implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4577429355064763313L;
	private long biId;
	private Catalog catalog;
	private String biHexColor;
	private String biSerial;
	private short biYear;
	private char biStatus;
	private char biGeoStatus;
	private Short biGeoRadius;
	private Double biGeoLat;
	private Double biGeoLon;
	private Set<Picture> pictures = new HashSet<Picture>(0);
	private Set<Track> tracks = new HashSet<Track>(0);
	private Set<Record> records = new HashSet<Record>(0);

	public Bike() {
	}

	public Bike(long biId, Catalog catalog, String biHexColor, String biSerial, short biYear, char biStatus,
			char biGeoStatus) {
		this.biId = biId;
		this.catalog = catalog;
		this.biHexColor = biHexColor;
		this.biSerial = biSerial;
		this.biYear = biYear;
		this.biStatus = biStatus;
		this.biGeoStatus = biGeoStatus;
	}

	public Bike(long biId, Catalog catalog, String biHexColor, String biSerial, short biYear, char biStatus,
			char biGeoStatus, Short biGeoRadius, Double biGeoLat, Double biGeoLon, Set<Picture> pictures,
			Set<Track> tracks, Set<Record> records) {
		this.biId = biId;
		this.catalog = catalog;
		this.biHexColor = biHexColor;
		this.biSerial = biSerial;
		this.biYear = biYear;
		this.biStatus = biStatus;
		this.biGeoStatus = biGeoStatus;
		this.biGeoRadius = biGeoRadius;
		this.biGeoLat = biGeoLat;
		this.biGeoLon = biGeoLon;
		this.pictures = pictures;
		this.tracks = tracks;
		this.records = records;
	}

	@Id
    @GeneratedValue(generator="InvSeq", strategy = GenerationType.SEQUENCE) 
    @SequenceGenerator(name="InvSeq", sequenceName="bike_bi_id_seq", allocationSize=1)
	@Column(name = "bi_id", unique = true, nullable = false)
	@JsonView(View.Summary.class)
	public long getBiId() {
		return this.biId;
	}

	public void setBiId(long biId) {
		this.biId = biId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ca_id", nullable = false)
	@JsonView(View.Summary.class)
	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@Column(name = "bi_hex_color", nullable = false, length = 7)
	@JsonView(View.Summary.class)
	public String getBiHexColor() {
		return this.biHexColor;
	}

	public void setBiHexColor(String biHexColor) {
		this.biHexColor = biHexColor;
	}

	@Column(name = "bi_serial", unique = true, nullable = false, length = 8)
	@JsonView(View.Summary.class)
		public String getBiSerial() {
		return this.biSerial;
	}

	public void setBiSerial(String biSerial) {
		this.biSerial = biSerial;
	}

	@Column(name = "bi_year", nullable = false)
	@JsonView(View.Summary.class)
	public short getBiYear() {
		return this.biYear;
	}

	public void setBiYear(short biYear) {
		this.biYear = biYear;
	}

	@Column(name = "bi_status", nullable = false, length = 1)
	@JsonView(View.Summary.class)
	public char getBiStatus() {
		return this.biStatus;
	}

	public void setBiStatus(char biStatus) {
		this.biStatus = biStatus;
	}

	@Column(name = "bi_geo_status", nullable = false, length = 1)
	@JsonView(View.Summary.class)
	public char getBiGeoStatus() {
		return this.biGeoStatus;
	}

	public void setBiGeoStatus(char biGeoStatus) {
		this.biGeoStatus = biGeoStatus;
	}

	@Column(name = "bi_geo_radius")
	@JsonView(View.Summary.class)
	public Short getBiGeoRadius() {
		return this.biGeoRadius;
	}

	public void setBiGeoRadius(Short biGeoRadius) {
		this.biGeoRadius = biGeoRadius;
	}

	@Column(name = "bi_geo_lat", precision = 17, scale = 17)
	@JsonView(View.Summary.class)
	public Double getBiGeoLat() {
		return this.biGeoLat;
	}

	public void setBiGeoLat(Double biGeoLat) {
		this.biGeoLat = biGeoLat;
	}

	@Column(name = "bi_geo_lon", precision = 17, scale = 17)
	@JsonView(View.Summary.class)
	public Double getBiGeoLon() {
		return this.biGeoLon;
	}

	public void setBiGeoLon(Double biGeoLon) {
		this.biGeoLon = biGeoLon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bike")
	public Set<Picture> getPictures() {
		return this.pictures;
	}

	public void setPictures(Set<Picture> pictures) {
		this.pictures = pictures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bike")
	public Set<Track> getTracks() {
		return this.tracks;
	}

	public void setTracks(Set<Track> tracks) {
		this.tracks = tracks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bike")
	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

}
