package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;
import com.hiveag.geepy.util.View;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name = "catalog", schema = "public")
public class Catalog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8281324665584747464L;
	private int caId;
	private Catalog catalog;
	private String caName;
	private char caType;
	private Set<Bike> bikes = new HashSet<Bike>(0);
	private Set<Catalog> catalogs = new HashSet<Catalog>(0);

	public Catalog() {
	}

	public Catalog(int caId, String caName, char caType) {
		this.caId = caId;
		this.caName = caName;
		this.caType = caType;
	}

	public Catalog(int caId, Catalog catalog, String caName, char caType, Set<Bike> bikes, Set<Catalog> catalogs) {
		this.caId = caId;
		this.catalog = catalog;
		this.caName = caName;
		this.caType = caType;
		this.bikes = bikes;
		this.catalogs = catalogs;
	}

	@Id
	@JsonView(View.Summary.class)
	@Column(name = "ca_id", unique = true, nullable = false)
	public int getCaId() {
		return this.caId;
	}

	public void setCaId(int caId) {
		this.caId = caId;
	}

	
	/**/
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ca_parent_id")
	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}
	
	
	@Column(name = "ca_name", nullable = false, length = 1024)
	@JsonView(View.Summary.class)
	public String getCaName() {
		return this.caName;
	}

	public void setCaName(String caName) {
		this.caName = caName;
	}
	
	
	@Column(name = "ca_type", nullable = false, length = 1)
	@JsonView(View.Summary.class)
	public char getCaType() {
		return this.caType;
	}

	public void setCaType(char caType) {
		this.caType = caType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalog")
	public Set<Bike> getBikes() {
		return this.bikes;
	}

	public void setBikes(Set<Bike> bikes) {
		this.bikes = bikes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalog")
	public Set<Catalog> getCatalogs() {
		return this.catalogs;
	}

	public void setCatalogs(Set<Catalog> catalogs) {
		this.catalogs = catalogs;
	}

}
