package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
public class Permission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4608985942532014275L;
	private short prId;
	private String prName;
	private String prResource;
	private Set<Assignment> assignments = new HashSet<Assignment>(0);

	public Permission() {
	}

	public Permission(short prId, String prName, String prResource) {
		this.prId = prId;
		this.prName = prName;
		this.prResource = prResource;
	}

	public Permission(short prId, String prName, String prResource, Set<Assignment> assignments) {
		this.prId = prId;
		this.prName = prName;
		this.prResource = prResource;
		this.assignments = assignments;
	}

	@Id

	@Column(name = "pr_id", unique = true, nullable = false)
	public short getPrId() {
		return this.prId;
	}

	public void setPrId(short prId) {
		this.prId = prId;
	}

	@Column(name = "pr_name", nullable = false, length = 20)
	public String getPrName() {
		return this.prName;
	}

	public void setPrName(String prName) {
		this.prName = prName;
	}

	@Column(name = "pr_resource", nullable = false, length = 50)
	public String getPrResource() {
		return this.prResource;
	}

	public void setPrResource(String prResource) {
		this.prResource = prResource;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<Assignment> getAssignments() {
		return this.assignments;
	}

	public void setAssignments(Set<Assignment> assignments) {
		this.assignments = assignments;
	}

}
