package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonView;
import com.hiveag.geepy.util.View;

/**
 * Picture generated by hbm2java
 */
@Entity
@Table(name = "picture", schema = "public")
public class Picture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5868578549704951984L;
	private PictureId id;
	private Bike bike;
	private Date piTimestamp;
	private String piPath;
 	
    private MultipartFile file;
    
	
	
	
	public Picture() {
	}

	public Picture(PictureId id, Bike bike, Date piTimestamp, String piPath) {
		this.id = id;
		this.bike = bike;
		this.piTimestamp = piTimestamp;
		this.piPath = piPath;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "biId", column = @Column(name = "bi_id", nullable = false)),
			@AttributeOverride(name = "piSlot", column = @Column(name = "pi_slot", nullable = false)) })
	@JsonView(View.Summary.class)
	public PictureId getId() {
		return this.id;
	}

	public void setId(PictureId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bi_id", nullable = false, insertable = false, updatable = false)
	public Bike getBike() {
		return this.bike;
	}

	public void setBike(Bike bike) {
		this.bike = bike;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pi_timestamp", nullable = false, length = 35)
	@JsonView(View.Summary.class)
	public Date getPiTimestamp() {
		return this.piTimestamp;
	}

	public void setPiTimestamp(Date piTimestamp) {
		this.piTimestamp = piTimestamp;
	}

	@Column(name = "pi_path", nullable = false, length = 50)
	@JsonView(View.Summary.class)
	public String getPiPath() {
		return this.piPath;
	}

	public void setPiPath(String piPath) {
		this.piPath = piPath;
	}

	
	
	

	@Transient
	@JsonIgnore
	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile files) {
		this.file = files;
	}
	
	
	
		
}
