package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonView;
import com.hiveag.geepy.util.View;

/**
 * Poi generated by hbm2java
 */
@Entity
@Table(name = "poi", schema = "public")
public class Poi implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 472854075173054734L;
	private long poId;
	private Person person;
	private String poName;
	private Long poPhNumber;
	private String poAddress;
	private double poLongitude;
	private double poLatitude;
	private short poScore;
	private char poType;

	public Poi() {
	}

	public Poi(long poId, Person person, String poName, double poLongitude, double poLatitude, short poScore,
			char poType) {
		this.poId = poId;
		this.person = person;
		this.poName = poName;
		this.poLongitude = poLongitude;
		this.poLatitude = poLatitude;
		this.poScore = poScore;
		this.poType = poType;
	}

	public Poi(long poId, Person person, String poName, Long poPhNumber, String poAddress, double poLongitude,
			double poLatitude, short poScore, char poType) {
		this.poId = poId;
		this.person = person;
		this.poName = poName;
		this.poPhNumber = poPhNumber;
		this.poAddress = poAddress;
		this.poLongitude = poLongitude;
		this.poLatitude = poLatitude;
		this.poScore = poScore;
		this.poType = poType;
	}

	@Id
	@JsonView(View.Summary.class)
	@Column(name = "po_id", unique = true, nullable = false)
    @GeneratedValue(generator="InvSeq", strategy = GenerationType.SEQUENCE) 
    @SequenceGenerator(name="InvSeq", sequenceName="poi_po_id_seq", allocationSize=1) 
	public long getPoId() {
		return this.poId;
	}

	public void setPoId(long poId) {
		this.poId = poId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pe_id", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "po_name", nullable = false, length = 100)
	@JsonView(View.Summary.class)
	public String getPoName() {
		return this.poName;
	}

	public void setPoName(String poName) {
		this.poName = poName;
	}

	@Column(name = "po_ph_number")
	@JsonView(View.Summary.class)
	public Long getPoPhNumber() {
		return this.poPhNumber;
	}

	public void setPoPhNumber(Long poPhNumber) {
		this.poPhNumber = poPhNumber;
	}

	@Column(name = "po_address", length = 60)
	@Size(min=5, max=60, message="{Size.Poi.poAddress.validation}") 
	@JsonView(View.Summary.class)
	public String getPoAddress() {
		return this.poAddress;
	}

	public void setPoAddress(String poAddress) {
		this.poAddress = poAddress;
	}

	@Column(name = "po_longitude", nullable = false, precision = 17, scale = 17)
	@JsonView(View.Summary.class)
	public double getPoLongitude() {
		return this.poLongitude;
	}

	public void setPoLongitude(double poLongitude) {
		this.poLongitude = poLongitude;
	}

	@Column(name = "po_latitude", nullable = false, precision = 17, scale = 17)
	@JsonView(View.Summary.class)
	public double getPoLatitude() {
		return this.poLatitude;
	}

	public void setPoLatitude(double poLatitude) {
		this.poLatitude = poLatitude;
	}

	@Column(name = "po_score", nullable = false)
	@JsonView(View.Summary.class)
	public short getPoScore() {
		return this.poScore;
	}

	public void setPoScore(short poScore) {
		this.poScore = poScore;
	}

	@Column(name = "po_type", nullable = false, length = 1)
	@JsonView(View.Summary.class)
	public char getPoType() {
		return this.poType;
	}

	public void setPoType(char poType) {
		this.poType = poType;
	}

}
