package com.hiveag.geepy.pojo;
// Generated May 29, 2017 4:55:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecordId generated by hbm2java
 */
@Embeddable
public class RecordId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3629415545762620502L;
	private long biId;
	private long geImei;

	public RecordId() {
	}

	public RecordId(long biId, long geImei) {
		this.biId = biId;
		this.geImei = geImei;
	}

	@Column(name = "bi_id", nullable = false)
	public long getBiId() {
		return this.biId;
	}

	public void setBiId(long biId) {
		this.biId = biId;
	}

	@Column(name = "ge_imei", nullable = false)
	public long getGeImei() {
		return this.geImei;
	}

	public void setGeImei(long geImei) {
		this.geImei = geImei;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecordId))
			return false;
		RecordId castOther = (RecordId) other;

		return (this.getBiId() == castOther.getBiId()) && (this.getGeImei() == castOther.getGeImei());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getBiId();
		result = 37 * result + (int) this.getGeImei();
		return result;
	}

}
